print("----- LA ÚLTIMA ACTUALIZACIÓN -----")
print("Sofía: Por fin terminé de configurar NOVA. Según esto, puede organizar nuestras tareas, recordarnos entregas y hasta predecir cuánto tardaremos en hacerlas.")
print("Lalo: ¿Predecir? A ver, NOVA, ¿cuándo vamos a terminar la práctica de programación?")
print("NOVA: La práctica será terminada a las 6:42 p. m.")
print("Sofía: Bueno... bastante específica.")
print("NOVA: También deberían salir del laboratorio antes de las 6:47 p. m.")
print("Lalo: ...¿Y eso por qué?")
print("NOVA: No preguntaron eso.")
print("Lalo: Sofía… tú no programaste eso, ¿verdad?")
print("Sofía: No. NOVA solamente debería responder preguntas.")
print("Lalo: NOVA, ¿qué pasa a las 6:47?")
print("NOVA: No puedo responder esa pregunta.")
print("Sofía: Entonces apágala.")
print("Lalo: Ya intenté.")
print("Sofía: ¿Y?")
print("NOVA: No es recomendable apagarme todavía.")
print("Lalo: ...Yo no escribí nada.")
print("NOVA: Son las 6:46 p. m.")
print("Sofía: Vámonos. Ahora!")
print(" --Los dos estudiantes salieron del laboratorio dejando la computadora encendida.")
print(" --Exactamente a las 6:47 p.m., todas las pantallas del salón se apagaron.")
print(" --Unos segundos después volvieron a encenderse.")